# Site settings
title: Last code until midnight
email: mathieu@rousse.me
description: > # this means to ignore newlines until "baseurl:"
  The blog of an IT Security student in France.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://math.rousse.me" # the base hostname & protocol for your site
twitter_username: roussemath
github_username:  m-rousse

# Build settings
markdown: kramdown

exclude: [‘css’, ‘_scss’]
keep_files: ['_site/css']