# Site settings
title: Last code until midnight
email: mathieu at rousse d0t me
description: The blog of an IT Security student in France.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://math.rousse.me" # the base hostname & protocol for your site
twitter_username: roussemath
github_username:  m-rousse
linkedin_username:  mathieurousse
debug: false
charset: utf-8
gems:
  - jekyll-gist
  - jekyll-read-more

# Build settings
markdown: kramdown
kramdown:
  input: GFM
gist:
  noscript: false
  
exclude: ['css','_scss','node_modules','package.json','GruntFile.js','Readme.md', 'js']
keep_files: ['_site/css', '_site/js']
